//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.HeThong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BDS()
        {
            this.GiaoDiches = new HashSet<GiaoDich>();
        }
    
        public int Id { get; set; }
        public string MaBDS { get; set; }
        public string Loai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string HinhAnhBDS { get; set; }
        public Nullable<double> DienTich { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> ChuSoHuuId { get; set; }
    
        public virtual ChuSoHuu ChuSoHuu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaoDich> GiaoDiches { get; set; }
    }
}
