//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.HeThong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDich
    {
        public int Id { get; set; }
        public string MaGD { get; set; }
        public Nullable<int> BDSId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public Nullable<System.DateTime> NgayGD { get; set; }
        public string LoaiGD { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BDS BD { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
